### PR TITLE
an anchor is a move point with a name

### PR DESCRIPTION
**Pull request by typemytype**
check if the point has a name

if no name is given its a single move point in a contour

### CODE REVIEW

**Comment by anthrotype** [comment]
hm.. yes, I remember something like that, but can't find reference to it in the UFO2 spec.
However if somebody bothered to even add a `testAnchor_legal_without_name`, it must have been done intentionally.

cc @typesupply @moyogo 

anyway, this only affects UFO2 right? And only when there's an open contour with a single point which doesn't have a "name" attribute.

**Comment by typemytype** [comment]
yes only UFO2 where the a single point contour has a name or not

the conversion from UFO2 to UFO3 goes wrong now

**Comment by typemytype** [comment]
see robofab: https://github.com/robofab-developers/robofab/blob/master/Lib/robofab/pens/rfUFOPen.py#L32-L33

**Comment by anthrotype** [comment]
> the conversion from UFO2 to UFO3 goes wrong now

and it has been wrong for a while..

**Comment by typemytype** [comment]
true!

try to open the test.ufo from glyph nanny https://github.com/typesupply/glyph-nanny
the single point is converted to a nameless anchor (and this goes wrong somewhere else in fontParts)

but it is not an anchor...:)

**Pull request merged**
