### PR TITLE
[pointPen] add identifier=None argument to AbstractPointPen methods

### PR DESCRIPTION
**Pull request by anthrotype**
Fixes https://github.com/unified-font-object/ufoLib/issues/62

I wonder if we should add `**kwargs` to `beginPath` and `addComponent` as well.
`AbstractPointPen.addPoint` has that already, and `glifLib.GLIFPointPen` also has that for `beginPath` and `addComponent`. 

(btw, I hate tabs)

### CODE REVIEW

**Comment by adrientetar** [comment]
Tabs are leftover from robofab (I didn't remove them), if you want to remove them please go ahead, Frederik already did that for reverse pen.

**Comment by anthrotype** [comment]
if we replace tabs with spaces everywhere then we screw `git blame`...

**Comment by typesupply** [comment]
> (btw, I hate tabs)

Me too. I know this was a conscious decision we made after a whole lot of discussion. It's ancient history now, but I think the issue was that the FontLab "macro" editor didn't do automatic indentation so each time we wrote a line we had to hit space four times or tab once. Then, using the arrows four navigation would require four hits per indentation level instead of one. Same with delete. It was a physical input issue.

**Comment by anthrotype** [comment]
nevermind the tabs.

what shall I do with `**kwargs?`? shall we add it to `beginPath` and `addComponent` too?

**Comment by typesupply** [comment]
> what shall I do with **kwargs?? shall we add it to beginPath and addComponent too?

The use of `**kwargs` at all for what I was trying to do is debatable. Here's what led to it... I was writing the drawPoints implementations in defcon and started sending out `identifier` arguments as needed. That then instantly broke a bunch of pens because most of the pens didn't know about `identifier` argument yet. So, I added the `try: ... except: DeprecationWarning` when a pen didn't accept identifiers. I thought this was a crude, limiting hack that wasn't going to scale well if the protocol added more stuff. (At the time, I was thinking that hints were going to pass through pens so there was real potential for lots of new args being added.) I came up with adding a catchall `**kwargs` at the end of the pen method implementations as a way to do some future proofing against pens needing to be updated if the protocol added a new arg. Later, I did this in FontParts for the same reasons. In that case, it made it hard to debug mistakes because keyword args could slip through with typos and whatnot. So, I took them out there and the consensus was that I made the right decision by removing it. So, now I'm not sure if we should keep these or not. FontParts is a simplified scripting API not a low level protocol implementation, so it's not a perfect comparison.

**Comment by adrientetar** [comment]
> if we replace tabs with spaces everywhere then we screw git blame...

if you blame on GitHub there's a new button "blame prior to that commit" now.

**Comment by anthrotype** [comment]
@typesupply hm, I see what you mean.
But `AbstractPointPen` already has kwargs in `addPoint`, and it's probably too late to remove that one.

**Comment by adrientetar** [comment]
kwargs in addPoint is useful when you have custom point attrs, e.g. point.selected.

**Comment by anthrotype** [comment]
> kwargs in addPoint is useful when you have custom point attrs, e.g. point.selected.

then I guess it could also be useful for contour's or component's custom attributes.

**Comment by typesupply** [comment]
> kwargs in addPoint is useful when you have custom point attrs, e.g. point.selected.

Yeah, hence my reluctance to say that they absolutely should be removed like I did in FontParts. Thinking about it a little more, I think that they are okay to use here. Not great, but okay given the chicken/egg scenario I mentioned above. PointPens are a low level thing that are mainly invoked directly by knowledgable developers. They aren't a bulletproof scripting API. So, I guess let's keep them.

**Comment by anthrotype** [comment]
> let's keep them.

sorry if ask for the third time.. do you mean, let's keep them in `addPoint` and also "let's add them to `beginPath` and `addComponent`"?

**Comment by typesupply** [comment]
Yes. Keep and add. Sorry, I'm under the weather and not communicating well.

**Comment by anthrotype** [comment]
one random Appveyor build failed for unrelated reason:
https://ci.appveyor.com/project/adrientetar/ufolib/build/1.0.157/job/frdwur5fr2lrsogx/messages

re-running it should pass.

gonna merge this now.

**Pull request merged**
