### PR TITLE
plistlib: reimplement as shim

### PR DESCRIPTION
**Pull request by adrientetar**
cc googlei18n/fontmake#38

### CODE REVIEW

**Comment by adrientetar** [comment]
@moyogo: Any idea why the ImportError on 2.7?

**Comment by moyogo** [comment]
@adrientetar + from __future__ import absolute_import
That fixes it for me.

Moving forward, it would be nice to have 'load' and 'dump' available as well.

**Comment by adrientetar** [comment]
Well readPlist/writePlist isn't bad naming either. I was concerned that we were using stdlib's plistlib in some places and the bundled one in others and that's why I pushed my previous PR. 
Around Python 3.2 there was a patch to emit empty plist elements to match OSX behavior so coming from different Python version there might be non-semantic changes in generated files.

**Comment by anthrotype** [comment]
I also think it would have been better if the py23 shim to plistlib was implemented using the python3 api (e.g. `load`, `dumps`). The old interface (readPlist, writePlist, etc.) could be exported as well for backward compatibility, but internally it would be more forward-looking to use the new interface.
Btw, both the stdlib `json` and the PyYAML modules use `dump` and `load`.

**Pull request merged**
