### PR TITLE
Allow duplicate kerning rules (non-conflicting)

### PR DESCRIPTION
**Pull request by jamesgk**

### CODE REVIEW

**Comment by jamesgk** [comment]
The way the validator is used in defcon, if kerning doesn't pass this validation it raises an exception on write, ufo2 load, and maybe other operations. It's kind of a pain when you have valid kerning but can't use the library because it's aggressively trying to clean things up for you (but not actually fixing things, just reporting issues).

Anyways, we are already forced to do some cleanup of kerning so it's not such a big deal to remove duplicates rules too. If this isn't a desired change I'm OK with closing it. cc @behdad because I think we discussed this (though I may have misunderstood what he wanted to do).

**Comment by behdad** [comment]
Let me clarify what I think should be fixed in ufoLib kern validator:

A conflict arises if a class-glyph and a glyph-class both match the same pair of glyphs, eg, if there's both a (public.kern1.A, B) kern pair, and a (A, public.kern2.B).

What I think should change is this:

  - If both kern pairs have the same kerning value (eg. both are -100), then there is no ambiguity and this should not be marked as an error,

  - Alternatively, if they do conflict, but a glyph-glyph kern pair for those two glyphs, eg (A, B), is also present, there is no conflict either since the glyph-glyph kerning trumps (or would that be drumpf?!) the glyph-class and class-glyph pairs.

Now, I agree that failing is a bit too harsh, would be nice if it was reduced to warnings.

**Comment by adrientetar** [comment]
@typesupply Any comments?

**Comment by typesupply** [comment]
I'm okay with this change. I'm actually a bit surprised that these values are out there in the wild.

I go back and forth on the warning vs. error issue. I made it raise exceptions because philosophically I didn't think it was right for a validator to fix something that was invalid. The reason that the validation happens at read/write is so that editors can know that they aren't getting noise during input or generating it on output. That was a big problem in the past as we were seeing bogus data and that meant that every editor had to do validation on its own or simply expect crashes.

If something can be quietly fixed in a logical, predictable way instead of raising the error, I'm okay with that now.

**Comment by typesupply** [comment]
One more thought, just to be clear: I absolutely stand against unresolvable conflicting or invalid data passing through the validator. Anything passing the validation check needs to be valid. The first situation @behdad pointed out isn't a conflict, it's just noise and the validator should ignore that. The second one is trickier. What if a user opens up that font, removes the glyph, glyph pair that resolves the conflict and then tries to save the file? (I don't have an answer. :)

**Comment by behdad** [comment]
The reason this is causing trouble for us is that Glyphs does not seem to fail on this.  So we receive .glyphs files, which we want to compile to fonts, and fail because of this check.  While failing to read/write invalid data is feasible for an all-UFO workflow where all editor go through this validation, the reality is far from this.

**Comment by behdad** [comment]
> The second one is trickier. What if a user opens up that font, removes the glyph, glyph pair that resolves the conflict and then tries to save the file? (I don't have an answer. :)

Then that makes the kerning set invalid.  It's not categorically different from any other modification that might make the kerning set invalid, is it?

**Comment by typesupply** [comment]
> The reason this is causing trouble for us is that Glyphs does not seem to fail on this. So we receive .glyphs files, which we want to compile to fonts, and fail because of this check. While failing to read/write invalid data is feasible for an all-UFO workflow where all editor go through this validation, the reality is far from this.

Ah. This is exactly what the validator was designed to catch. I really don't want to allow environment specific "quirks" into loaded objects. Every environment will have to know about every other environment's quirks and bugs. We tried that before and it led to the calcification in RoboFab. It's fine to add a little thing here and there at the beginning, but as years go by they add up into something that is incredibly difficult to update. It's also fine as long as there is one reader/writer, but as soon as there is another that is following the spec, that reader/writer won't have the environment specific handling.

In this case, is the data being loaded by glyphs2ufo? If so, could you do a check [here](https://github.com/googlei18n/glyphs2ufo/blob/master/Lib/glyphs2ufo/torf.py#L491) and coerce the data?

**Comment by behdad** [comment]
I believe @jamesgk is working around this validation error by discarding problematic kerning pairs earlier on, at least in fontmake / ufo2ft, maybe not glyphs2ufo.

I understand the usefulness of validation.  But there's also value to being able to read invalid data and write it out intact.  That is not always possible, but in this case, of course.

Anyway, I'm not arguing for one resolution or another here, just presenting what we have been seeing in this area.

**Pull request closed without merging**
