### PR TITLE
Set up CI to run pytest with tox; prepare auto-deployment

### PR DESCRIPTION
**Pull request by anthrotype**
This PR enables running the test suite with [pytest](https://pytest.org), and also sets up the Travis and Appveyor CI to check the package installation and run the tests in isolated virtual environments using [Tox](https://tox.readthedocs.io/en/latest/).
It also prepares Travis for uploading distribution packages automatically upon tags, though the latter is commented-out as the authentication requires someone with push access to the repo

***

Since at least [December 2011](https://github.com/robofab-developers/robofab/commit/f9ec29518c13dfb8a83e040a13a96b47b759a011), robofab has had the version string in the setup.py frozen at `1.2`.
Its spin-off package, ufoLib has inherited the version after the separation, and has kept it like that even after the ufo3 branch was merged a few months ago in master.

ufoLib is a dependency of several other packages, like defcon, ufo2ft, cu2qu, fontMath and booleanOperations (see my graph [here](https://github.com/behdad/fonttools/pull/648#issuecomment-246107751)). So it is a crucial piece in the open source font production toolchain.

When using ufoLib for font production, it is of critical importance to being able to pin down the exact set of requirements needed for building a particular revision of a particular font; as well as being able to reproduce the same result in the future, or on a different local machine or server.

This is why we need an easy, maintainable way for ufoLib developers to release, package and deploy the library for users and other developers to consume in the way they are already familiar with other more mature python projects: that is, installed through pip from the [Python Package Index](https://pypi.org) (PyPI), with clear semantic versions that allow to track and resolve dependencies, freeze and recreate environments, ... [insert here my usual packaging sermon].

I already did something similar with fonttools, compreffor, booleanOperations, and I plan to do it for all the other packages as well.

Tal, I know you are busy. If you grant me push access to this and the other repositories of yours (defcon, fontMath), I can more easily help you out making continuous integration and deployment up and running.
Thank you.

### CODE REVIEW

**Comment by anthrotype** [comment]
Thanks Adrien.

You noticed I set the version to `2.0.dev1`. I hope it doesn't stay like that for another 5 years now. ;)

Jokes apart, I was planning to remove the pre-release suffix only when the auto-deployment is correctly set up. That's because in my experience it usually requires a few attempts to get it working, and also because on PyPI you can't upload the same file twice, so the distributions must have unique filenames, which in turn is generated based on the version string.. I hope it makes sense.

If you have spare time I can assist you setting up the Travis deploy section.

**Comment by moyogo** [comment]
Great!

**Comment by adrientetar** [comment]
Let's see if Tal comes in.

**Comment by typesupply** [comment]
> Let's see if Tal comes in.

I'll read through this when I get to my desk this morning. Thanks!

**Comment by typesupply** [comment]
This all looks great to me!

> Tal, I know you are busy. If you grant me push access to this and the other repositories of yours (defcon, fontMath), I can more easily help you out making continuous integration and deployment up and running.

This would be fantastic. Email me and let me know which repositories you want access to and I'll set it up.

**Pull request merged**
