### PR TITLE
When converting kerning group names, remove the older '@MMK' prefixes

### PR DESCRIPTION
**Pull request by andyclymer**
Fix for issue #118

### CODE REVIEW

**Comment by benkiel** [comment]
Looks like test data needs to be updated

**Comment by adrientetar** [comment]
No but this will add a diff when round-tripping from ufo2 (not that it matters, I guess).

**Comment by benkiel** [comment]
@adrientetar thank you; seems a reasonable tradeoff to cleanup vendor specific prefixes when they aren't needed in version 3

**Comment by LettError** [comment]
Thanks!

**Pull request merged**
