### PR TITLE
glifLib: open files as binary to avoid line-endings normalization

### PR DESCRIPTION
**Pull request by adrientetar**

### CODE REVIEW

**Comment by anthrotype** [comment]
we should check all the usages of `open` function and make them consistently read/write bytes then.
but we should also take care of decoding/encoding bytes to/from unicode if we do that.

**Comment by anthrotype** [comment]
precisely...
```
TypeError: 'str' does not support the buffer interface
```

**Comment by anthrotype** [comment]
welcome to the `py23` hell ;)

**Comment by adrientetar** [comment]
Do you want to patch this?

**Comment by anthrotype** [comment]
yes, I can. But it's going to take a while..

I counted 110 uses of `open`

```
$ git grep "open(" | wc -l
     110
$ git grep "open(\(.*, \"wb\"\)" | wc -l
      50
$ git grep "open(\(.*, \"w\"\)" | wc -l
       9
$ git grep "open(\(.*, \"r\"\)" | wc -l
       6
$ git grep "open(\(.*, \"rb\"\)" | wc -l
      42
```

**Comment by anthrotype** [comment]
Maybe we should also have a module like fonttools' `py23` as a compatibility layer which common functions to deal with bytes vs unicode. Or maybe simply use fonttools' one.

**Comment by adrientetar** [comment]
Thanks. To fix all open and so forth, we can probe by breaking: write a test that outputs all non-ASCII data that you can possibly usee in a UFO e.g. glyphname and fix everything that breaks.

**Pull request merged**
